### ISSUE TITLE
子项目循环引用

### ISSUE THREAD

**Issue by harris2012** [leaferjs/leafer#1]
![image](https://github.com/leaferjs/leafer/assets/12846977/c8f957db-dc70-45f2-af09-6768f3de1f07)

**Comment by leaferjs** [comment]
谢谢反馈，已修复～

**Comment by harris2012** [comment]
看起来master上面仍然存在依赖关系

1. platform 依赖 layouter
https://github.com/leaferjs/leafer/blob/main/packages/platform/platform/package.json

2. layouter 依赖 event
https://github.com/leaferjs/leafer/blob/main/packages/layouter/package.json

3. event 依赖 decorator
https://github.com/leaferjs/leafer/blob/main/packages/event/event/package.json

4. decorator 依赖 platform
https://github.com/leaferjs/leafer/blob/main/packages/decorator/package.json
